### ISSUE TITLE
Companion is gone...

### ISSUE THREAD

**Issue by Zetta-Zerena** [simwr872/RSAPI#1]
Companion being gone makes a lot of people mad... 1 of my phone's (rooted LG) still sends me ge messages when buy/sell hits good or completed. Does this work like companion did? I'm looking for 1 and 1 that has a bot in it too...

**Comment by simwr872** [comment]
Unfortunately since Jagex is adamant on updating the params for the game every week, this tool will cease to exist. I spent some time before trying to use [the normal parameters](https://world5.runescape.com/k=0/jav_config.ws) but without luck. Most of these parameters will stay the same after an update (urls, ports, worlds) but with another order. However, there are atleast 2 that are different from the normal game and comapp that are hash-like.

Even if we would have these parameters the actual code (bootstrap.js) gets re-mangled after sometime and refuse to work, hence working with an old copy would be useless.
